# Generated by Django 3.2.16 on 2024-07-01 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_alter_recipesingredients_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='users.myuser', verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
