# Generated by Django 3.2.16 on 2024-07-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipes_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='color',
        ),
    ]
