# Generated by Django 3.2.16 on 2024-07-12 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20240712_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredients',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
