# Generated by Django 3.2.16 on 2024-06-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/images/'),
        ),
    ]
